// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dependencies

import (
	"acy.com/api/src/db"
	"acy.com/api/src/repositories"
	"acy.com/api/src/services"
)

// Injectors from wire.go:

func InitializeAlbumService() *services.AlbumService {
	sqlDB := db.PostgresDbProvider()
	albumRepository := repositories.NewAlbumRepository(sqlDB)
	albumService := services.NewAlbumService(albumRepository)
	return albumService
}

func InitializeAlbumMongoDBService() *services.AlbumMongoService {
	database := db.GetMongoDb()
	albumMongoDBRepository := repositories.NewAlbumMongoDBRepository(database)
	albumMongoService := services.NewAlbumMongoService(albumMongoDBRepository)
	return albumMongoService
}
