package main

import (
	"net/http"

	"acy.com/api/src/controllers"
	libs "acy.com/api/src/lib"
	"acy.com/api/src/middlewares"
	"github.com/gin-gonic/gin"

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "acy.com/api/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title           Swagger ACY API
// @version         1.0
// @description     This is a web api server.
// @termsOfService  http://swagger.io/terms/

// @contact.name   API Support
// @contact.url    http://www.swagger.io/support
// @contact.email  support@swagger.io

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html
// @BasePath  /api/v1
// @query.collection.format multi
func main() {
	logger := libs.NewZapLogger()
	r := gin.New() // disable default router and some common middleware
	r.Use(middlewares.GinLogger(logger), middlewares.GinRecovery(logger, true))

	r.GET("/", func(c *gin.Context) {
		c.String(http.StatusOK, "Hello world!")
	})

	// you can customize swagger settings
	config := &ginSwagger.Config{
		Title: "ACY Golang Training API",
		URL: "http://localhost:3000/swagger/doc.json", //The url pointing to API definition
	}

	// docs route
	r.GET("/swagger/*any", ginSwagger.CustomWrapHandler(config, swaggerFiles.Handler))

	v1 := r.Group("/api/v1")
	{
		admin := v1.Group("/albums")

		admin.GET("/", controllers.GetAlbums)
		admin.GET("/:id", controllers.GetAlbumById)
		admin.POST("/", controllers.CreateAlbum)
		admin.DELETE("/:id", controllers.DeleteAlbumById)
	}

	err := r.Run(":3000")

	if err != nil {
		panic(err.Error())
	}
}
